--DDl

CREATE DATABASE SENAI_HROADS_TARDE
GO

USE SENAI_HROADS_TARDE
GO

CREATE TABLE TiposHabilidade(
		IdTipo INT PRIMARY KEY IDENTITY,
		NomeTipo VARCHAR(500) NOT NULL
)
GO

CREATE TABLE Habilidades
(
IdHabilidade INT PRIMARY KEY IDENTITY
,IdTipo INT FOREIGN KEY REFERENCES TiposHabilidade(IdTipo)
,NomeHabilidade VARCHAR(100) NOT NULL
)
GO

CREATE TABLE Classes
(
IdClasse INT PRIMARY KEY IDENTITY
,NomeClasse VARCHAR(100)
)
GO


CREATE TABLE ClassesHabilidade
(
IdClasse INT FOREIGN KEY REFERENCES Classes(IdClasse)
,IdHabilidade INT FOREIGN KEY REFERENCES Habilidades(IdHabilidade)
)
GO


CREATE TABLE Personagens
(
IdPersonagem INT PRIMARY KEY IDENTITY
,IdClasse INT FOREIGN KEY REFERENCES Classes(IdClasse)
,NomePersonagem VARCHAR(200) NOT NULL
,CapacidadeMAXVida VARCHAR(300) NOT NULL
,CapacidadeMAXMana VARCHAR(300) NOT NULL
,DataAtualizacao VARCHAR(200) NOT NULL
,DataCriacao VARCHAR(300) NOT NULL
);
GO

CREATE TABLE TiposUsuario(
	IdTipoUsuario	INT PRIMARY KEY IDENTITY,
	Tipo			VARCHAR(200) NOT NULL				
);
GO

CREATE TABLE Usuarios(
	IdUsuario		INT PRIMARY KEY IDENTITY,
	IdTipoUsuario	INT FOREIGN KEY REFERENCES TiposUsuario(idTipoUsuario),
	Nome			VARCHAR(200) NOT NULL,
	Email			VARCHAR(200) UNIQUE NOT NULL,
	Senha			VARCHAR(200) NOT NULL
);
GO


